media: media
content:
  - name: pages
    label: Pages
    type: collection
    path: docs
    fields:
      - name: title
        type: string
      - name: author
        type: string
      - name: categories
        type: string
        list: true
      - name: body
        type: rich-text